draw_config:
  key_w: 80
  key_h: 80
  split_gap: 0.0
  combo_w: 30
  combo_h: 30
  key_rx: 4.0
  key_ry: 4.0
  dark_mode: auto
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 1
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: false
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: false
  key_side_pars:
    rel_x: 0.0
    rel_y: 4.0
    rel_w: 12.0
    rel_h: 16.0
    rx: 4.0
    ry: 4.0
  svg_extra_style: '
    svg.keymap {
      font-family: system-ui, sans-serif;
      font-size: 20px;
      font-weight: 600;
    }

    text.label {
      font-size: 32px;
    }

    text.combo {
      font-size: 18px;
    }

    text.shifted,
    text.hold {
      font-size: 16px;
    }

    text.layer-indicator {
      font-size: 14px;
    }

    text.footer {
      font-size: 14px;
      text-weight: 400;
    }

    .trans,
    .ghost,
    .none {
      opacity: 0.9;
    }

    path.combo {
      stroke-width: 2px;
    }

    rect.combo, rect.combo-separate {
      fill: #d7a7ac;
    }

    rect.held, rect.combo.held {
      fill: #ffd35c;
    }

    .mdi\:circle-off-outline {
      opacity: 0.32
    }

    @media (prefers-color-scheme: dark) {
      rect.combo, rect.combo-separate {
        fill: #772953;
      }

      rect.held, rect.combo.held {
        fill: #91506c;
      }
    }
  '
  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 20
  glyph_hold_size: 16
  glyph_shifted_size: 16
  glyphs: {}

parse_config:
  preprocess: true
  skip_binding_parsing: false
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend:
    tap: $$mdi:circle-off-outline$$
    type: trans
  layer_legend_map: {}
  mark_alternate_layer_activators: false
  modifier_fn_map:
    left_ctrl: Ctl
    right_ctrl: Ctl
    left_shift: Sft
    right_shift: Sft
    left_alt: Alt
    right_alt: AltGr
    left_gui: Gui
    right_gui: Gui
    keycode_combiner: '{mods}+{key}'
    mod_combiner: '{mod_1}+{mod_2}'
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  qmk_remove_keycode_prefix:
  - KC_
  qmk_keycode_map:
    XXXXXXX: ''
    'NO': ''
    MINUS: '-'
    MINS: '-'
    EQUAL: '='
    EQL: '='
    LEFT_BRACKET: '['
    LBRC: '['
    RIGHT_BRACKET: ']'
    RBRC: ']'
    BACKSLASH: \
    BSLS: \
    NONUS_HASH: '#'
    NUHS: '#'
    SEMICOLON: ;
    SCLN: ;
    QUOTE: ''''
    QUOT: ''''
    GRAVE: '`'
    GRV: '`'
    COMMA: ','
    COMM: ','
    DOT: .
    SLASH: /
    SLSH: /
    TILDE: '~'
    TILD: '~'
    EXCLAIM: '!'
    EXLM: '!'
    AT: '@'
    HASH: '#'
    DOLLAR: $
    DLR: $
    PERCENT: '%'
    PERC: '%'
    CIRCUMFLEX: ^
    CIRC: ^
    AMPERSAND: '&'
    AMPR: '&'
    ASTERISK: '*'
    ASTR: '*'
    LEFT_PAREN: (
    LPRN: (
    RIGHT_PAREN: )
    RPRN: )
    UNDERSCORE: _
    UNDS: _
    PLUS: +
    LEFT_CURLY_BRACE: '{'
    LCBR: '{'
    RIGHT_CURLY_BRACE: '}'
    RCBR: '}'
    PIPE: '|'
    COLON: ':'
    COLN: ':'
    DOUBLE_QUOTE: '"'
    DQUO: '"'
    DQT: '"'
    LEFT_ANGLE_BRACKET: <
    LABK: <
    LT: <
    RIGHT_ANGLE_BRACKET: '>'
    RABK: '>'
    GT: '>'
    QUESTION: '?'
    QUES: '?'
  zmk_remove_keycode_prefix: []
  raw_binding_map:
    "&Tab_Caps":
      tap: $$mdi:keyboard-tab$$
      hold: $$mdi:apple-keyboard-caps$$ # technically double tap
    "&key_repeat":
      tap: $$mdi:repeat$$
  zmk_keycode_map:
    # Partially inspired by caksoylar/zmk-config + minusfive/knucklehead

    # Sound/Media
    C_MUTE: $$mdi:volume-off$$
    K_MUTE: $$mdi:volume-off$$
    C_VOL_UP: $$mdi:volume-high$$
    K_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$
    K_VOL_DN: $$mdi:volume-low$$
    C_NEXT: $$mdi:skip-next$$
    K_NEXT: $$mdi:skip-next$$
    C_PREV: $$mdi:skip-previous$$
    K_PREV: $$mdi:skip-previous$$
    C_PP: $$mdi:play-pause$$
    K_PP: $$mdi:play-pause$$

    # Modifiers
    LCTRL: $$mdi:apple-keyboard-control$$
    RCTRL: $$mdi:apple-keyboard-control$$

    LALT: $$mdi:apple-keyboard-option$$
    RALT: $$mdi:apple-keyboard-option$$

    LSHIFT: $$mdi:apple-keyboard-shift$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$

    LCMD: $$mdi:apple-keyboard-command$$
    RCMD: $$mdi:apple-keyboard-command$$
    RGUI: $$mdi:apple-keyboard-command$$
    LGUI: $$mdi:apple-keyboard-command$$

    ESC: $$mdi:keyboard-esc$$
    SPACE: $$mdi:keyboard-space$$

    LC(BACKSPACE): # erase word
      type: backspace
      tap: $$mdi:backspace$$
    BACKSPACE: # normal backspace
      type: backspace
      tap: $$mdi:backspace-outline$$
    LC(BSPC): # erase word
      type: backspace
      tap: $$mdi:backspace$$
    BSPC: # normal backspace
      type: backspace
      tap: $$mdi:backspace-outline$$

    TAB: $$mdi:keyboard-tab$$

    RET:
      type: enter
      tap: $$mdi:keyboard-return$$
    ENTER:
      type: enter
      tap: $$mdi:keyboard-return$$

    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$

    INS: Insert
    HOME: Home
    END: End
    CAPS: $$mdi:apple-keyboard-caps$$
    PSCRN: Print Scrn
    PAUSE_BREAK: Pause Break

    # Arrows
    UP: $$mdi:arrow-up$$
    DOWN: $$mdi:arrow-down$$
    LEFT: $$mdi:arrow-left$$
    RIGHT: $$mdi:arrow-right$$

    PG_UP: $$mdi:pan-up$$
    PG_DN: $$mdi:pan-down$$

    LC(C): $$mdi:content-copy$$
    LC(V): $$mdi:content-paste$$
    LC(X): $$mdi:content-cut$$

    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH:
      tap: "/"
      shifted: "?"
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: \
    BSLH: \
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON:
      tap: ";"
      shifted: ":"
    SEMI:
      tap: ";"
      shifted: ":"
    COLON: ':'
    SINGLE_QUOTE:
      tap: "'"
      shifted: '"'
    SQT:
      tap: "'"
      shifted: '"'
    APOSTROPHE: ''''
    APOS: ''''
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ','
    LESS_THAN: <
    LT: <
    DOT:
      tap: "."
      shifted: ">"
    COMMA:
      tap: ","
      shifted: "<"
    GREATER_THAN: ">"
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
  zmk_combos:
    combo_ret:
      draw_separate: true
    combo_cut:
      rotation: 45
  zmk_preamble: '#define KEYMAP_DRAWER'
  zmk_additional_includes: []
