name: Build firmware
on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - "config/*.keymap"
      - "config/*.conf"
      - "config/*.dtsi"
      # - 'boards/*/*/*.keymap'

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
